sudo: required
language: generic
services:
  -docker # spesify Docker dependency

before_install: # build test imanges
  - docker build -t esaito01/react-test -f ./client/Dockerfile.dev ./client

script: #Run tests
#  - docker run esaito01/react-test npm test -- --coverage
   - docker run -e CI=true esaito01/react-test npm test

after_success: #build Prod images
  - docker build -t esaito01/multi-client ./client
  - docker build -t esaito01/multi-nginx ./nginx
  - docker build -t esaito01/multi-server ./server
  - docker build -t esaito01/multi-worker ./worker
#log in to docker CLI from Travis platform
  - echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin
#Travis build Test image and test it
  - docker push esaito01/multi-client
  - docker push esaito01/multi-nginx
  - docker push esaito01/multi-server
  - docker push esaito01/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker' # in elasticBeansTalk
  env:  'Multidocker-env'  # in elasticBeansTalk
  bucket_name: 'elasticbeanstalk-ap-northeast-1-561130388491' # in S3
  bucket_path:  'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

